"""empty message

Revision ID: 0da2290338d7
Revises: dd71851b79ec
Create Date: 2020-10-30 21:08:02.518296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da2290338d7'
down_revision = 'dd71851b79ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrateur', sa.Column('is_superadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrateur', 'is_superadmin')
    # ### end Alembic commands ###
