"""empty message

Revision ID: 521a59ca8c78
Revises: b191a89929a7
Create Date: 2020-10-31 19:45:47.923390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '521a59ca8c78'
down_revision = 'b191a89929a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matiere', sa.Column('professeur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matiere', 'professeur', ['professeur_id'], ['id'])
    op.drop_constraint('professeur_ibfk_1', 'professeur', type_='foreignkey')
    op.drop_column('professeur', 'matiere_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professeur', sa.Column('matiere_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('professeur_ibfk_1', 'professeur', 'matiere', ['matiere_id'], ['id'])
    op.drop_constraint(None, 'matiere', type_='foreignkey')
    op.drop_column('matiere', 'professeur_id')
    # ### end Alembic commands ###
