"""empty message

Revision ID: b191a89929a7
Revises: f0324c207a0f
Create Date: 2020-10-31 15:03:07.157422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b191a89929a7'
down_revision = 'f0324c207a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_administrateur_username', table_name='administrateur')
    op.drop_column('administrateur', 'username')
    op.drop_index('ix_etudiant_username', table_name='etudiant')
    op.drop_column('etudiant', 'username')
    op.drop_index('ix_professeur_username', table_name='professeur')
    op.drop_column('professeur', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professeur', sa.Column('username', mysql.VARCHAR(length=60), nullable=True))
    op.create_index('ix_professeur_username', 'professeur', ['username'], unique=True)
    op.add_column('etudiant', sa.Column('username', mysql.VARCHAR(length=60), nullable=True))
    op.create_index('ix_etudiant_username', 'etudiant', ['username'], unique=True)
    op.add_column('administrateur', sa.Column('username', mysql.VARCHAR(length=60), nullable=True))
    op.create_index('ix_administrateur_username', 'administrateur', ['username'], unique=True)
    # ### end Alembic commands ###
