"""empty message

Revision ID: ba45d5632db8
Revises: eeeff01cca85
Create Date: 2020-10-30 16:51:05.060219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba45d5632db8'
down_revision = 'eeeff01cca85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrateur', sa.Column('date_naissance', sa.Date(), nullable=True))
    op.create_index(op.f('ix_administrateur_date_naissance'), 'administrateur', ['date_naissance'], unique=False)
    op.drop_index('ix_administrateur_Date_naissane', table_name='administrateur')
    op.drop_column('administrateur', 'Date_naissane')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrateur', sa.Column('Date_naissane', sa.DATE(), nullable=True))
    op.create_index('ix_administrateur_Date_naissane', 'administrateur', ['Date_naissane'], unique=False)
    op.drop_index(op.f('ix_administrateur_date_naissance'), table_name='administrateur')
    op.drop_column('administrateur', 'date_naissance')
    # ### end Alembic commands ###
