"""empty message

Revision ID: dce02c094a91
Revises: ba45d5632db8
Create Date: 2020-10-30 16:52:40.884387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce02c094a91'
down_revision = 'ba45d5632db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiant', sa.Column('date_naissance', sa.Date(), nullable=True))
    op.create_index(op.f('ix_etudiant_date_naissance'), 'etudiant', ['date_naissance'], unique=False)
    op.drop_index('ix_etudiant_Date_naissane', table_name='etudiant')
    op.drop_column('etudiant', 'Date_naissane')
    op.add_column('professeur', sa.Column('date_naissance', sa.Date(), nullable=True))
    op.create_index(op.f('ix_professeur_date_naissance'), 'professeur', ['date_naissance'], unique=False)
    op.drop_index('ix_professeur_Date_naissane', table_name='professeur')
    op.drop_column('professeur', 'Date_naissane')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professeur', sa.Column('Date_naissane', sa.DATE(), nullable=True))
    op.create_index('ix_professeur_Date_naissane', 'professeur', ['Date_naissane'], unique=False)
    op.drop_index(op.f('ix_professeur_date_naissance'), table_name='professeur')
    op.drop_column('professeur', 'date_naissance')
    op.add_column('etudiant', sa.Column('Date_naissane', sa.DATE(), nullable=True))
    op.create_index('ix_etudiant_Date_naissane', 'etudiant', ['Date_naissane'], unique=False)
    op.drop_index(op.f('ix_etudiant_date_naissance'), table_name='etudiant')
    op.drop_column('etudiant', 'date_naissance')
    # ### end Alembic commands ###
