"""empty message

Revision ID: eeeff01cca85
Revises: 
Create Date: 2020-10-30 16:15:29.632731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeeff01cca85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_departement', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_departement')
    )
    op.create_table('administrateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_admin', sa.String(length=60), nullable=True),
    sa.Column('prenom_admin', sa.String(length=60), nullable=True),
    sa.Column('sexe_admin', sa.String(length=60), nullable=True),
    sa.Column('Date_naissane', sa.Date(), nullable=True),
    sa.Column('email_admin', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrateur_Date_naissane'), 'administrateur', ['Date_naissane'], unique=False)
    op.create_index(op.f('ix_administrateur_email_admin'), 'administrateur', ['email_admin'], unique=True)
    op.create_index(op.f('ix_administrateur_nom_admin'), 'administrateur', ['nom_admin'], unique=False)
    op.create_index(op.f('ix_administrateur_prenom_admin'), 'administrateur', ['prenom_admin'], unique=False)
    op.create_index(op.f('ix_administrateur_sexe_admin'), 'administrateur', ['sexe_admin'], unique=False)
    op.create_index(op.f('ix_administrateur_username'), 'administrateur', ['username'], unique=True)
    op.create_table('formation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_formation', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_formation')
    )
    op.create_table('etudiant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_etud', sa.String(length=60), nullable=True),
    sa.Column('prenom_etud', sa.String(length=60), nullable=True),
    sa.Column('sexe_etud', sa.String(length=60), nullable=True),
    sa.Column('Date_naissane', sa.Date(), nullable=True),
    sa.Column('email_etud', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formation_id'], ['formation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etudiant_Date_naissane'), 'etudiant', ['Date_naissane'], unique=False)
    op.create_index(op.f('ix_etudiant_email_etud'), 'etudiant', ['email_etud'], unique=True)
    op.create_index(op.f('ix_etudiant_nom_etud'), 'etudiant', ['nom_etud'], unique=False)
    op.create_index(op.f('ix_etudiant_prenom_etud'), 'etudiant', ['prenom_etud'], unique=False)
    op.create_index(op.f('ix_etudiant_sexe_etud'), 'etudiant', ['sexe_etud'], unique=False)
    op.create_index(op.f('ix_etudiant_username'), 'etudiant', ['username'], unique=True)
    op.create_table('matiere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_matiere', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formation_id'], ['formation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_matiere')
    )
    op.create_table('annonce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('titre', sa.String(length=200), nullable=True),
    sa.Column('contenu', sa.String(length=400), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formation_id'], ['formation.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matiere.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.Column('titre', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('fichier', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matiere_id'], ['matiere.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professeur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_prof', sa.String(length=60), nullable=True),
    sa.Column('prenom_prof', sa.String(length=60), nullable=True),
    sa.Column('sexe_prof', sa.String(length=60), nullable=True),
    sa.Column('Date_naissane', sa.Date(), nullable=True),
    sa.Column('email_prof', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matiere_id'], ['matiere.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professeur_Date_naissane'), 'professeur', ['Date_naissane'], unique=False)
    op.create_index(op.f('ix_professeur_email_prof'), 'professeur', ['email_prof'], unique=True)
    op.create_index(op.f('ix_professeur_nom_prof'), 'professeur', ['nom_prof'], unique=False)
    op.create_index(op.f('ix_professeur_prenom_prof'), 'professeur', ['prenom_prof'], unique=False)
    op.create_index(op.f('ix_professeur_sexe_prof'), 'professeur', ['sexe_prof'], unique=False)
    op.create_index(op.f('ix_professeur_username'), 'professeur', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professeur_username'), table_name='professeur')
    op.drop_index(op.f('ix_professeur_sexe_prof'), table_name='professeur')
    op.drop_index(op.f('ix_professeur_prenom_prof'), table_name='professeur')
    op.drop_index(op.f('ix_professeur_nom_prof'), table_name='professeur')
    op.drop_index(op.f('ix_professeur_email_prof'), table_name='professeur')
    op.drop_index(op.f('ix_professeur_Date_naissane'), table_name='professeur')
    op.drop_table('professeur')
    op.drop_table('cours')
    op.drop_table('annonce')
    op.drop_table('matiere')
    op.drop_index(op.f('ix_etudiant_username'), table_name='etudiant')
    op.drop_index(op.f('ix_etudiant_sexe_etud'), table_name='etudiant')
    op.drop_index(op.f('ix_etudiant_prenom_etud'), table_name='etudiant')
    op.drop_index(op.f('ix_etudiant_nom_etud'), table_name='etudiant')
    op.drop_index(op.f('ix_etudiant_email_etud'), table_name='etudiant')
    op.drop_index(op.f('ix_etudiant_Date_naissane'), table_name='etudiant')
    op.drop_table('etudiant')
    op.drop_table('formation')
    op.drop_index(op.f('ix_administrateur_username'), table_name='administrateur')
    op.drop_index(op.f('ix_administrateur_sexe_admin'), table_name='administrateur')
    op.drop_index(op.f('ix_administrateur_prenom_admin'), table_name='administrateur')
    op.drop_index(op.f('ix_administrateur_nom_admin'), table_name='administrateur')
    op.drop_index(op.f('ix_administrateur_email_admin'), table_name='administrateur')
    op.drop_index(op.f('ix_administrateur_Date_naissane'), table_name='administrateur')
    op.drop_table('administrateur')
    op.drop_table('departement')
    # ### end Alembic commands ###
