"""empty message

Revision ID: f0324c207a0f
Revises: a539d5f6d615
Create Date: 2020-10-31 05:53:06.597654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0324c207a0f'
down_revision = 'a539d5f6d615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrateur', sa.Column('is_superadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrateur', 'is_superadmin')
    # ### end Alembic commands ###
